plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'fabric-loom' version '1.8-SNAPSHOT' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.30-beta' apply false
    id 'net.darkhax.curseforgegradle' version "${curseforgegradle_version}" apply false // curseforge publishing
    id "com.modrinth.minotaur" version "2.+" apply false // modrinth publishing
}

task publishCurseForge(dependsOn: [':fabric:publishCurseForge', ':neoforge:publishCurseForge']) {
}
task publishModrinth(dependsOn: [':fabric:modrinth', ':neoforge:modrinth']) {
}
task publishCurseAndModrinth(dependsOn: ['publishCurseForge', 'publishModrinth']) {
}