# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=2.0.1-beta.3
group=de.leximon
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Fluidlogged
mod_author=Leximon
mod_id=fluidlogged
license=MIT
credits=MoreThanHidden, PricelessKoala
description=Allows \"fluidlogging\" for any block by storing fluids separately in each chunk. Fluids can now also pass through blocks!
minecraft_version_range=[1.21.1, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.11.10
asm_version=9.2
lombok_version=1.18.30

# Fabric
fabric_version=0.109.0+1.21.1
fabric_loader_version=0.16.9

# NeoForge
neoforge_version=21.1.80
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# CurseForgeGradle & Minotaur
curseforgegradle_version=1.1.25
mod_version_suffix=mc1.21.1
mod_version_type=beta
mod_game_versions=["1.21.1"]
modrinth_project_id=BnXpPaut
curseforge_project_id=620894
debug_publish=true

# Dependencies
modmenu_version=11.0.0
yacl_version=3.5.0+1.21
sodium_version=mc1.21.1-0.6.5
lithium_version=mc1.21.1-0.14.3
