plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

dependencies {
    // YACL provides no common artifact. Use neoforge artifact as common one to build against
    compileOnly("dev.isxander:yet-another-config-lib:${yacl_version}-neoforge") {
        exclude group: 'com.terraformersmc'
    }
    compileOnly "maven.modrinth:sodium:${sodium_version}-neoforge"
    compileOnly "maven.modrinth:lithium:${lithium_version}-neoforge"
    compileOnly "org.ow2.asm:asm:${asm_version}"
    compileOnly "org.ow2.asm:asm-tree:${asm_version}"
    compileOnly "org.ow2.asm:asm-util:${asm_version}"
    compileOnly "org.checkerframework:checker-qual:3.12.0"
    
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    
    compileOnly "org.projectlombok:lombok:${lombok_version}"
    annotationProcessor "org.projectlombok:lombok:${lombok_version}"
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

