modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"
issueTrackerURL="https://github.com/Leximon/Fluidlogged/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL="https://github.com/Leximon/Fluidlogged"
logoFile="${mod_id}.png"
credits="${credits}"
authors = "${mod_author}"
description = '''${description}'''

[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

[[dependencies.${mod_id}]] #optional
modId = "neoforge" #mandatory
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[${neoforge_version},)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
[[dependencies.${mod_id}]]
modId = "minecraft"
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neoforge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="yet_another_config_lib_v3"
    type="optional"
    versionRange = "[3.5.0+1.21,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="sodium"
    type="optional"
    versionRange = "[0.6.0-beta,)"
    ordering="NONE"
    side="CLIENT"
