name: Build Fluidlogged
on: [ pull_request, push ]

jobs:
  build:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '[CI-SKIP]') == false
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Gradle Build Fabric
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: Fabric:build

      - name: Capture Build Artifacts Fabric
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts Fabric
          path: fabric/build/libs/*.jar

      - name: Gradle Build Forge
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: Forge:build

      - name: Capture Build Artifacts Forge
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts Forge
          path: forge/build/libs/*.jar
